import type { BlockedSite, BlockerSchedule } from "@/types";

const MARKER_START = "# >>> flowstate-block >>>";
const MARKER_END = "# <<< flowstate-block <<<";

function domainVariants(domain: string): string[] {
  const bare = domain.replace(/^www\./, "");
  return [bare, `www.${bare}`];
}

/**
 * Generates a self-contained macOS/Linux bash script that toggles a hosts-file
 * block for the given domains. Must be run locally with sudo — this app has
 * no way to reach the user's actual machine from the browser or from a cloud
 * session, so the user installs and runs this themselves.
 */
export function generateBlockerScript(sites: BlockedSite[]): string {
  const domains = [...new Set(sites.flatMap((s) => domainVariants(s.domain)))].sort();
  const domainList = domains.map((d) => `  "${d}"`).join("\n");

  return `#!/usr/bin/env bash
# FlowState site blocker — generated by the FlowState app.
# Blocks the domains below at the OS level (all browsers/apps) by redirecting
# them to localhost in /etc/hosts. Requires sudo because /etc/hosts is
# root-owned. Re-download this script from Settings whenever you change your
# blocklist in the app.
#
# Usage:
#   sudo ./flowstate-block.sh on       # start blocking
#   sudo ./flowstate-block.sh off      # stop blocking
#   ./flowstate-block.sh status        # check current state

set -euo pipefail

HOSTS_FILE="/etc/hosts"
MARKER_START="${MARKER_START}"
MARKER_END="${MARKER_END}"

DOMAINS=(
${domainList}
)

flush_dns() {
  if command -v dscacheutil >/dev/null 2>&1; then
    dscacheutil -flushcache 2>/dev/null || true
    killall -HUP mDNSResponder 2>/dev/null || true
  elif command -v systemd-resolve >/dev/null 2>&1; then
    systemd-resolve --flush-caches 2>/dev/null || true
  elif command -v resolvectl >/dev/null 2>&1; then
    resolvectl flush-caches 2>/dev/null || true
  fi
}

strip_block() {
  if grep -q "$MARKER_START" "$HOSTS_FILE" 2>/dev/null; then
    sed -i.flowstate.bak "/$MARKER_START/,/$MARKER_END/d" "$HOSTS_FILE"
    rm -f "$HOSTS_FILE.flowstate.bak"
  fi
}

block_on() {
  # Re-running 'on' always syncs to the domain list baked into this script —
  # it never silently no-ops just because a block was already present, so
  # re-downloading after changing your blocklist in the app "just works."
  local was_blocking=0
  if grep -q "$MARKER_START" "$HOSTS_FILE" 2>/dev/null; then
    was_blocking=1
    strip_block
  fi
  {
    echo "$MARKER_START"
    for d in "\${DOMAINS[@]}"; do
      echo "127.0.0.1 $d"
      echo "::1 $d"
    done
    echo "$MARKER_END"
  } >> "$HOSTS_FILE"
  flush_dns
  if [ "$was_blocking" = "1" ]; then
    echo "Blocklist updated. Now blocking \${#DOMAINS[@]} domain(s): \${DOMAINS[*]}"
  else
    echo "Blocking \${#DOMAINS[@]} domain(s): \${DOMAINS[*]}"
  fi
}

block_off() {
  if ! grep -q "$MARKER_START" "$HOSTS_FILE" 2>/dev/null; then
    echo "Not currently blocking."
    exit 0
  fi
  strip_block
  flush_dns
  echo "Blocking removed."
}

block_status() {
  if grep -q "$MARKER_START" "$HOSTS_FILE" 2>/dev/null; then
    echo "Blocking is ON:"
    sed -n "/$MARKER_START/,/$MARKER_END/p" "$HOSTS_FILE"
  else
    echo "Blocking is OFF."
  fi
}

case "\${1:-}" in
  on) block_on ;;
  off) block_off ;;
  status) block_status ;;
  *)
    echo "Usage: sudo $0 {on|off|status}"
    exit 1
    ;;
esac
`;
}

/**
 * Generates a root LaunchDaemon plist that auto-runs the blocker script at
 * the configured start/end times on the configured days (macOS only).
 * Must be placed at /Library/LaunchDaemons/ and loaded with sudo — see the
 * install instructions shown alongside the download in Settings.
 */
export function generateLaunchdPlist(schedule: BlockerSchedule, scriptAbsolutePath: string): string {
  function intervalsFor(time: string, days: number[]) {
    const [hour, minute] = time.split(":").map(Number);
    return days
      .map(
        (weekday) => `    <dict>
      <key>Weekday</key><integer>${weekday}</integer>
      <key>Hour</key><integer>${hour}</integer>
      <key>Minute</key><integer>${minute}</integer>
    </dict>`
      )
      .join("\n");
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.flowstate.blocker.on</string>
  <key>ProgramArguments</key>
  <array>
    <string>${scriptAbsolutePath}</string>
    <string>on</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
${intervalsFor(schedule.startTime, schedule.days)}
  </array>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
`;
}

export function generateLaunchdOffPlist(schedule: BlockerSchedule, scriptAbsolutePath: string): string {
  function intervalsFor(time: string, days: number[]) {
    const [hour, minute] = time.split(":").map(Number);
    return days
      .map(
        (weekday) => `    <dict>
      <key>Weekday</key><integer>${weekday}</integer>
      <key>Hour</key><integer>${hour}</integer>
      <key>Minute</key><integer>${minute}</integer>
    </dict>`
      )
      .join("\n");
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.flowstate.blocker.off</string>
  <key>ProgramArguments</key>
  <array>
    <string>${scriptAbsolutePath}</string>
    <string>off</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
${intervalsFor(schedule.endTime, schedule.days)}
  </array>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
`;
}

/** A stable fingerprint of just the domain list, so the UI can tell you when the downloaded script drifts out of sync — separate from the schedule so editing one doesn't falsely flag the other as stale. */
export function getSitesFingerprint(sites: BlockedSite[]): string {
  const domains = [...new Set(sites.map((s) => s.domain))].sort();
  return JSON.stringify(domains);
}

/** A stable fingerprint of just the schedule, for the plist download sync indicator. */
export function getScheduleFingerprint(schedule: BlockerSchedule): string {
  return JSON.stringify(schedule);
}

export function downloadTextFile(filename: string, contents: string) {
  const blob = new Blob([contents], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
